using System.Text;

var outDir = @"D:\geomatics_task\地理信息工程及应用\czt_geohazrd_system\cztApp_Solution\docs";

string Img(string name) => $"![](screenshots/{name})";

// ========== 功能设计.md ==========
var md = new StringBuilder();
md.AppendLine("# 功能设计");
md.AppendLine();
md.AppendLine("截图放在 screenshots/ 目录下。");
md.AppendLine();
md.AppendLine("---");
md.AppendLine();
md.AppendLine("## 1. 启动界面");
md.AppendLine();
md.AppendLine("程序启动时显示品牌启动屏，3.2 秒后自动进入主界面。");
md.AppendLine();
md.AppendLine(Img("01-splash.png"));
md.AppendLine();
md.AppendLine("## 2. 主界面");
md.AppendLine();
md.AppendLine("Ribbon 工具栏在上，左侧数据面板，中间地图，右侧面板，底部状态栏。");
md.AppendLine();
md.AppendLine(Img("02-main.png"));
md.AppendLine();
md.AppendLine("## 3. 数据管理面板");
md.AppendLine();
md.AppendLine("左侧面板，连接本地空间数据文件夹后展示目录树。双击SHP加载到地图，右键菜单操作。");
md.AppendLine();
md.AppendLine(Img("03-data-panel.png"));
md.AppendLine();
md.AppendLine("## 4. 图层面板");
md.AppendLine();
md.AppendLine("管理已加载图层。每行含复选框、名称、符号色块。悬停浅蓝底，选中深蓝边框。");
md.AppendLine();
md.AppendLine(Img("04-layer-panel.png"));
md.AppendLine();
md.AppendLine("## 5. 符号系统面板");
md.AppendLine();
md.AppendLine("编辑图层渲染样式。单一符号可调填充色/透明度/轮廓色。按字段配色选字段和色带自动渲染。");
md.AppendLine();
md.AppendLine(Img("05-symbol.png"));
md.AppendLine();
md.AppendLine("## 6. 地理分析面板");
md.AppendLine();
md.AppendLine("五个分析模块共用。选分类面图层和灾害点图层，选字段，运行分析，输出CF值统计表和图表。");
md.AppendLine();
md.AppendLine(Img("06-geo-panel.png"));
md.AppendLine();
md.AppendLine("## 7. 属性浏览");
md.AppendLine();
md.AppendLine("选图层即可查看属性表，支持复制选中行和导出CSV。");
md.AppendLine();
md.AppendLine(Img("07-attr-browse.png"));
md.AppendLine();
md.AppendLine("## 8. 属性编辑");
md.AppendLine();
md.AppendLine("可编辑DataGrid直接修改属性值，保存写回SHP文件。支持添加字段和撤销修改。");
md.AppendLine();
md.AppendLine(Img("08-attr-manage.png"));
md.AppendLine();
md.AppendLine("## 9. 属性查询");
md.AppendLine();
md.AppendLine("按条件查询属性表，支持等于、不等于、模糊匹配、大于、小于等运算符。");
md.AppendLine();
md.AppendLine(Img("09-attr-query.png"));
md.AppendLine();
md.AppendLine("## 10. 空间查询");
md.AppendLine();
md.AppendLine("两个图层之间的空间关系查询，支持相交和完全包含两种方式。");
md.AppendLine();
md.AppendLine(Img("10-spatial-query.png"));
md.AppendLine();
md.AppendLine("## 11. 专题制图");
md.AppendLine();
md.AppendLine("选图层、输图名、刷新底图。画布上自动生成地图底图、真实图例、比例尺、指北针，均可鼠标拖动定位，最后生成PNG。");
md.AppendLine();
md.AppendLine(Img("11-thematic.png"));
md.AppendLine();
md.AppendLine("## 12. 统计图查看");
md.AppendLine();
md.AppendLine("浏览分析输出的PNG统计图，缩略图预览，点击打开原图。");
md.AppendLine();
md.AppendLine(Img("12-stat-chart.png"));
md.AppendLine();
md.AppendLine("## 13. 统计表查看");
md.AppendLine();
md.AppendLine("浏览分析输出的CSV统计表，点击在DataGrid中预览内容。");
md.AppendLine();
md.AppendLine(Img("13-stat-table.png"));
md.AppendLine();
md.AppendLine("## 14. 视图菜单");
md.AppendLine();
md.AppendLine("标题栏视图下拉菜单，切换四个面板和地图视图的显隐状态。");
md.AppendLine();
md.AppendLine(Img("14-view-menu.png"));
md.AppendLine();
md.AppendLine("## 15. 状态栏");
md.AppendLine();
md.AppendLine("实时显示操作状态、地图比例尺和鼠标所在位置的经纬度坐标。");
md.AppendLine();
md.AppendLine(Img("15-status-bar.png"));

File.WriteAllText(Path.Combine(outDir, "功能设计.md"), md.ToString(), Encoding.UTF8);
Console.WriteLine("DONE: 功能设计.md");

// ========== 界面设计.md ==========
md.Clear();
md.AppendLine("# 界面设计");
md.AppendLine();
md.AppendLine("截图放在 screenshots/ 目录下。");
md.AppendLine();
md.AppendLine("---");
md.AppendLine();
md.AppendLine("## 色彩");
md.AppendLine();
md.AppendLine("| 用途 | 色值 |");
md.AppendLine("|------|------|");
md.AppendLine("| 主题色 | #1565C0 |");
md.AppendLine("| 选中边框 | #0D47A1 |");
md.AppendLine("| 悬停 | #BBDEFB |");
md.AppendLine("| 选中背景 | #E3F2FD |");
md.AppendLine("| 窗口背景 | #F2F2F2 |");
md.AppendLine("| 面板背景 | #FBFBFB |");
md.AppendLine("| 边框 | #C8C8C8 |");
md.AppendLine("| 正文 | #1A1A1A |");
md.AppendLine();
md.AppendLine("## 字体");
md.AppendLine();
md.AppendLine("全系统 Microsoft YaHei UI，标题 11pt，正文 10pt，表格 9pt。");
md.AppendLine();
md.AppendLine("## 启动界面");
md.AppendLine();
md.AppendLine("深色背景(#1B1F2B)，居中显示系统全称，底部三个圆点依次闪烁。");
md.AppendLine();
md.AppendLine(Img("ui-01.png"));
md.AppendLine();
md.AppendLine("## 主窗口布局");
md.AppendLine();
md.AppendLine("标题栏、Ribbon三页签、左侧数据面板、中央地图、右侧图层面板，底部状态栏。");
md.AppendLine();
md.AppendLine(Img("ui-02.png"));
md.AppendLine();
md.AppendLine("## 数据面板");
md.AppendLine();
md.AppendLine("顶部连接文件夹按钮和路径显示，绿色生成属性表按钮，搜索框，空间/属性切换标签，目录树。");
md.AppendLine();
md.AppendLine(Img("ui-03.png"));
md.AppendLine();
md.AppendLine("## 图层面板");
md.AppendLine();
md.AppendLine("每行含复选框、图层名、符号预览色块。悬停浅蓝底，选中深蓝边框。");
md.AppendLine();
md.AppendLine(Img("ui-04.png"));
md.AppendLine();
md.AppendLine("## 符号面板");
md.AppendLine();
md.AppendLine("上半部分预览和属性编辑，下半部分按字段配色。");
md.AppendLine();
md.AppendLine(Img("ui-05.png"));
md.AppendLine();
md.AppendLine("## 地理分析面板");
md.AppendLine();
md.AppendLine("图层选择、字段选择、分级分区、分析方法、输出目录、运行按钮。结果区含柱状图、CF汇总、DataGrid表格。");
md.AppendLine();
md.AppendLine(Img("ui-06.png"));
md.AppendLine();
md.AppendLine("## 专题制图面板");
md.AppendLine();
md.AppendLine("图层选择、图名输入、画布预览（地图底图+可拖动图例+比例尺+指北针）、生成按钮。");
md.AppendLine();
md.AppendLine(Img("ui-07.png"));
md.AppendLine();
md.AppendLine("## 属性浏览 / 编辑 / 查询");
md.AppendLine();
md.AppendLine("属性浏览：选择图层查看属性表。属性编辑：可编辑DataGrid、保存、撤销。属性查询：条件查询。");
md.AppendLine();
md.AppendLine(Img("ui-08.png"));
md.AppendLine();
md.AppendLine("## 空间查询");
md.AppendLine();
md.AppendLine("目标图层和源图层选择，相交/包含查询方式。");
md.AppendLine();
md.AppendLine(Img("ui-09.png"));
md.AppendLine();
md.AppendLine("## 统计图 / 统计表");
md.AppendLine();
md.AppendLine("查看已生成的PNG统计图和CSV统计表。");
md.AppendLine();
md.AppendLine(Img("ui-10.png"));
md.AppendLine();
md.AppendLine("## 右键菜单");
md.AppendLine();
md.AppendLine("数据面板右键：添加地图、缩放、属性浏览、属性。图层面板右键：缩放、符号、属性浏览、排序、移除。");
md.AppendLine();
md.AppendLine(Img("ui-11.png"));
md.AppendLine();
md.AppendLine("## 视图菜单");
md.AppendLine();
md.AppendLine("标题栏视图下拉，切换面板和地图视图的显隐。");
md.AppendLine();
md.AppendLine(Img("ui-12.png"));
md.AppendLine();
md.AppendLine("## 状态栏");
md.AppendLine();
md.AppendLine("左侧操作状态和图层数，中间实时比例尺，右侧实时鼠标经纬度坐标。");
md.AppendLine();
md.AppendLine(Img("ui-13.png"));

File.WriteAllText(Path.Combine(outDir, "界面设计.md"), md.ToString(), Encoding.UTF8);
Console.WriteLine("DONE: 界面设计.md");
