using System.Text;

var imgDir = @"D:\geomatics_task\地理信息工程及应用\截图";
var outDir = @"D:\geomatics_task\地理信息工程及应用\czt_geohazrd_system\cztApp_Solution\docs";

string Img(string name)
{
    var path = Path.Combine(imgDir, name);
    if (!File.Exists(path)) return $"MISSING: {name}";
    var bytes = File.ReadAllBytes(path);
    var b64 = Convert.ToBase64String(bytes);
    return $"![](data:image/png;base64,{b64})";
}

var md = new StringBuilder();
md.AppendLine("# 界面设计");
md.AppendLine();
md.AppendLine("## 色彩");
md.AppendLine();
md.AppendLine("| 用途 | 色值 |");
md.AppendLine("|------|------|");
md.AppendLine("| 主题色 | #1565C0 |");
md.AppendLine("| 选中边框 | #0D47A1 |");
md.AppendLine("| 悬停 | #BBDEFB |");
md.AppendLine("| 选中背景 | #E3F2FD |");
md.AppendLine("| 窗口背景 | #F2F2F2 |");
md.AppendLine("| 面板背景 | #FBFBFB |");
md.AppendLine("| 边框 | #C8C8C8 |");
md.AppendLine("| 正文 | #1A1A1A |");
md.AppendLine();
md.AppendLine("## 字体");
md.AppendLine();
md.AppendLine("全系统 Microsoft YaHei UI，标题 11pt，正文 10pt，表格 9pt。");
md.AppendLine();
md.AppendLine("## 启动界面");
md.AppendLine();
md.AppendLine("深色背景(#1B1F2B)，居中显示系统全称，底部三个圆点依次闪烁。");
md.AppendLine();
md.AppendLine(Img("启动界面.png"));
md.AppendLine();
md.AppendLine("## 主窗口布局");
md.AppendLine();
md.AppendLine("标题栏、Ribbon三页签、左侧数据面板、中央地图、右侧图层面板，底部状态栏。");
md.AppendLine();
md.AppendLine(Img("主界面.png"));
md.AppendLine();
md.AppendLine("## 数据面板");
md.AppendLine();
md.AppendLine("顶部连接文件夹按钮和路径显示，绿色生成属性表按钮，搜索框，空间/属性切换标签，目录树。");
md.AppendLine();
md.AppendLine(Img("数据管理面板.png"));
md.AppendLine();
md.AppendLine("## 图层面板");
md.AppendLine();
md.AppendLine("每行含复选框、图层名、符号预览色块。悬停浅蓝底，选中深蓝边框。");
md.AppendLine();
md.AppendLine(Img("图层面板.png"));
md.AppendLine();
md.AppendLine("## 符号面板");
md.AppendLine();
md.AppendLine("上半部分预览和属性编辑，下半部分按字段配色。");
md.AppendLine();
md.AppendLine(Img("符号系统.png"));
md.AppendLine();
md.AppendLine("## 地理分析面板");
md.AppendLine();
md.AppendLine("图层选择、字段选择、分级分区、分析方法、输出目录、运行按钮。结果区含柱状图、CF汇总、DataGrid表格。");
md.AppendLine();
md.AppendLine(Img("地理分析土壤植被.png"));
md.AppendLine();
md.AppendLine("## 专题制图面板");
md.AppendLine();
md.AppendLine("图层选择、图名输入、画布预览（地图底图+可拖动图例+比例尺+指北针）、生成按钮。");
md.AppendLine();
md.AppendLine(Img("专题制图.png"));
md.AppendLine();
md.AppendLine("## 属性浏览 / 编辑 / 查询");
md.AppendLine();
md.AppendLine("属性浏览：选择图层查看属性表。属性编辑：可编辑DataGrid、保存、撤销。属性查询：条件查询。");
md.AppendLine();
md.AppendLine(Img("属性浏览.png"));
md.AppendLine();
md.AppendLine(Img("属性管理（属性编辑）.png"));
md.AppendLine();
md.AppendLine(Img("属性查询.png"));
md.AppendLine();
md.AppendLine("## 空间查询");
md.AppendLine();
md.AppendLine("目标图层和源图层选择，相交/包含查询方式。");
md.AppendLine();
md.AppendLine(Img("空间查询.png"));
md.AppendLine();
md.AppendLine("## 统计图 / 统计表");
md.AppendLine();
md.AppendLine("查看已生成的PNG统计图和CSV统计表。");
md.AppendLine();
md.AppendLine(Img("统计图.png"));
md.AppendLine();
md.AppendLine(Img("统计表.png"));
md.AppendLine();
md.AppendLine("## 右键菜单");
md.AppendLine();
md.AppendLine("数据面板右键：添加地图、缩放、属性浏览、属性。图层面板右键：缩放、符号、属性浏览、排序、移除。");
md.AppendLine();
md.AppendLine(Img("右键菜单.png"));
md.AppendLine();
md.AppendLine("## 视图菜单");
md.AppendLine();
md.AppendLine("标题栏视图下拉，切换数据面板、地图视图、图层面板、符号系统、地理处理的显隐。");
md.AppendLine();
md.AppendLine(Img("视图菜单.png"));
md.AppendLine();
md.AppendLine("## 状态栏");
md.AppendLine();
md.AppendLine("左侧操作状态和图层数，中间实时比例尺，右侧实时鼠标经纬度坐标。");
md.AppendLine();
md.AppendLine(Img("状态栏.png"));
md.AppendLine();
md.AppendLine("## 地图面板");
md.AppendLine();
md.AppendLine("ArcGIS Runtime 地图视图，WGS84坐标系，白底无网格，支持矢量面/线/点和栅格图层叠加显示。");
md.AppendLine();
md.AppendLine(Img("地图面板.png"));

File.WriteAllText(Path.Combine(outDir, "界面设计.md"), md.ToString(), Encoding.UTF8);
Console.WriteLine("DONE");
